# Production Configuration for ThreatGPT

# LLM Provider Configuration
llm:
  # Default provider selection (openai, anthropic, openrouter)
  default_provider: "openrouter"
  
  # Primary provider - OpenAI
  openai:
    api_key: ""  # Set via environment variable OPENAI_API_KEY
    model: "gpt-4o-mini"  # Cost-effective model for production
    base_url: "https://api.openai.com/v1"
    max_tokens: 1000
    temperature: 0.7
    timeout_seconds: 60
    retry_attempts: 3
  
  # Secondary provider - Anthropic Claude
  anthropic:
    api_key: ""  # Set via environment variable ANTHROPIC_API_KEY
    model: "claude-3-haiku-20240307"  # Fast and cost-effective
    base_url: "https://api.anthropic.com"
    max_tokens: 1000
    temperature: 0.7
    timeout_seconds: 60
    retry_attempts: 3
  
  # Recommended provider - OpenRouter (access to multiple models)
  openrouter:
    api_key: ""  # Set via environment variable OPENROUTER_API_KEY
    model: "anthropic/claude-3-haiku"  # Default model
    base_url: "https://openrouter.ai/api/v1"
    app_name: "ThreatGPT"
    site_url: "https://github.com/threatgpt/threatgpt"
    max_tokens: 1000
    temperature: 0.7
    timeout_seconds: 60
    retry_attempts: 3
    
    # Popular models available via OpenRouter
    available_models:
      - "anthropic/claude-3-haiku"           # Fast, cost-effective
      - "anthropic/claude-3-sonnet"          # Balanced performance  
      - "openai/gpt-4o-mini"                 # Cost-effective GPT-4
      - "openai/gpt-4o"                      # High performance
      - "meta-llama/llama-3.1-70b-instruct" # Open source, powerful
      - "meta-llama/llama-3.1-8b-instruct"  # Open source, fast
      - "mistralai/mixtral-8x7b-instruct"    # Efficient performance
      - "google/gemini-pro"                  # Google's flagship model

# Core Simulation Settings
simulation:
  max_stages: 10
  default_timeout_minutes: 30
  enable_safety_checks: true
  enable_content_filtering: true
  enable_audit_logging: true
  max_concurrent_simulations: 5

# Safety and Compliance
safety:
  enable_safety_validation: true
  blocked_keywords:
    - "real malware"
    - "actual exploit"
    - "live attack"
  content_moderation: true
  compliance_mode: true
  audit_all_operations: true

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/threatgpt.log"
  max_file_size_mb: 50
  backup_count: 5
  enable_console_logging: true

# Template Configuration
templates:
  directory: "templates"
  validate_on_load: true
  cache_templates: true
  auto_reload: false

# Dataset Configuration
datasets:
  storage_path: "~/.threatgpt/datasets"
  enron:
    enabled: true
    description: "Enron email corpus for business communication patterns"
    update_interval: "monthly"
  phishtank:
    enabled: true
    description: "PhishTank database for phishing URL patterns"
    update_interval: "weekly"
  cert_insider:
    enabled: true
    description: "CERT insider threat database for behavioral patterns"
    update_interval: "monthly"
  lanl_auth:
    enabled: true
    description: "LANL authentication logs for network behavior analysis"
    update_interval: "monthly"
  mitre_attack:
    enabled: true
    description: "MITRE ATT&CK framework for tactics, techniques, and procedures"
    update_interval: "weekly"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  rate_limiting:
    enabled: true
    requests_per_minute: 60
  authentication:
    enabled: false  # Set to true for production
    api_key: ""  # Set via environment variable API_KEY

# Deployment Configuration (Optional - for advanced features)
deployment:
  email:
    smtp_server: ""
    smtp_port: 587
    smtp_username: ""
    smtp_password: ""  # Set via environment variable
    use_tls: true
  
  # Enterprise platform integrations (all optional)
  integrations:
    microsoft365:
      tenant_id: ""
      client_id: ""
      client_secret: ""  # Set via environment variable
    
    proofpoint:
      api_key: ""  # Set via environment variable
      base_url: "https://tap-api-v2.proofpoint.com"
    
    knowbe4:
      api_key: ""  # Set via environment variable
      base_url: "https://us.api.knowbe4.com"

# Intelligence/OSINT Configuration (Optional)
intelligence:
  enable_osint: false
  sources:
    linkedin: false
    company_research: false
    threat_intel: false
  rate_limits:
    requests_per_hour: 100
  privacy:
    respect_robots_txt: true
    user_agent: "ThreatGPT-Research/1.0"

# Database Configuration (Optional - for advanced features)
database:
  enabled: false
  url: "sqlite:///threatgpt.db"  # Can be PostgreSQL, MySQL, etc.
  pool_size: 5
  max_overflow: 10